"""add extracted text

Revision ID: 11ec259f6ff7
Revises: e7e569bdda09
Create Date: 2026-07-01 23:33:02.310455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11ec259f6ff7'
down_revision: Union[str, Sequence[str], None] = 'e7e569bdda09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('text', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('extracted_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'extracted_text')
    op.drop_column('documents', 'text')
    # ### end Alembic commands ###
